apiVersion: v1
kind: Service
metadata:
  name: {{ include "catalog-api.fullname" . }}
  labels:
    {{- include "catalog-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "catalog-api.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.env.port }}
