image:
  repository: 540828371641.dkr.ecr.sa-east-1.amazonaws.com/catalog-api
  tag: "dev"
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:sa-east-1:540828371641:certificate/CERTIFICATE_ID
  hosts:
    - host: api.dev.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: catalog-api-tls
      hosts:
        - api.dev.example.com

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

podSecurityContext:
  fsGroup: 2000

securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]

serviceAccount:
  create: true
  name: ""
  annotations: {}
env:
  secretName: catalog-api-secrets
  port: 8080

networkPolicy:
  enabled: true

pdb:
  enabled: true
  minAvailable: 1
