image:
  repository: 540828371641.dkr.ecr.sa-east-1.amazonaws.com/catalog-api
  tag: "dev"

ingress:
  hosts:
    - host: api.dev.example.com
      paths:
        - path: /
          pathType: Prefix

replicaCount: 2
hpa:
  enabled: true
