apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catalog-stage
  namespace: argocd
spec:
  project: portfolio
  source:
    repoURL: https://github.com/cilsocarvalho/catalog-api-node-eks-argocd.git
    targetRevision: main
    path: charts/catalog-api
    helm:
      releaseName: catalog-stage
      valueFiles:
        - ../../envs/stage/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: catalog-stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true